# Creating NumPy arrays

In [ ]:
import numpy as np

Create the following NumPy arrays:

```pythons
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

In [ ]:
np.arange(10)

```pythons
array([0. , 1.25, 2.5 , 3.75, 5. ])
```

In [ ]:
np.linspace(0, 5, 5)

```pythons
array([ 1, 3, 12, 92])
```

In [ ]:
np.array([1, 3, 12, 92])

```pythons
array([[1, 2, 3, 4],
       [5, 6, 7, 8]])
```

In [ ]:
np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

```pythons
array([[[0, 2, 4, 6],
        [1, 3, 5, 7]],

       [[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[9, 8, 7, 6],
        [5, 4, 3, 2]]])
```

In [ ]:
np.array(
    [
        [[0, 2, 4, 6], [1, 3, 5, 7]],
        [[1, 2, 3, 4], [5, 6, 7, 8]],
        [[9, 8, 7, 6], [5, 4, 3, 2]],
    ]
)

In [ ]:
np.array(
    [
        [range(0, 7, 2), range(1, 8, 2)],
        [range(1, 5), range(5, 9)],
        [range(9, 5, -1), range(5, 1, -1)],
    ]
)

A $2\times 8$ array containing uniformly distributed random numbers in $[0, 1)$.

In [ ]:
np.random.rand(2, 8)

```pythons
array([[1st, 0th, 0th],
       [0th, 1st, 0th],
       [0th, 0th, 1st]])
```

In [ ]:
np.eye(3)

A vector of length 5 containing normally distributed numbers.

In [ ]:
np.random.standard_normal(5)

A $3 \times 4$ array containing normally distributed numbers with mean $5$ and standard deviation $0.5$.

In [ ]:
np.random.normal(5, 0.5, (3, 4))

## Systems of equations

Solve the following system of equations:

$x_1 - x_2 + 2x_3 = 6$

$2x_1 + 3x_2 + 2x_3 = 8$

$3x_1 + 2x_2 + x_3 = 8$

In [ ]:
a = np.array([[1.0, -1.0, 2.0], [2.0, 3.0, 2.0], [3.0, 2.0, 1.0]])
b = np.array([6.0, 8.0, 8.0])

In [ ]:
import scipy.linalg as linalg

lu = linalg.lu_factor(a)

In [ ]:
x = linalg.lu_solve(lu, b)

In [ ]:
x

In [ ]:
a.dot(x)

# Create NumPy arrays 2

Create the following NumPy array:

```pythons
array([[ 0, 2, 4, 6],
       [8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30],
       [32, 34, 36, 38]])
```

In [ ]:
np.arange(0, 40, 2).reshape(5, 4)

Create the following NumPy array:

```pythons
array([[10, 19, 28, 37, 46, 55],
       [13, 22, 31, 40, 49, 58],
       [16, 25, 34, 43, 52, 61]])
```

In [ ]:
np.arange(10, 64, 3).reshape(3, 6, order="F")

# Extreme values

Generate a vector of length 100 containing random values equally
distributed in the interval $[10, 20)$.

Calculate minimum and maximum of the values
contained in the vector as well as the indices of minimum and maximum.

In [ ]:
vec = np.random.random(100) * 10 + 10
vec[:10]

In [ ]:
vec.min()

In [ ]:
vec.argmin()

In [ ]:
vec.max()

In [ ]:
vec.argmax()


# Average

Create a $6 \times 8$ array with numbers normally distributed with
mean $2$ and standard deviation $1$.

In [ ]:
my_array = np.random.normal(2.0, 1.0, (6, 8))

Calculate the mean of all values in the array.

In [ ]:
my_array.mean()

Calculate the row and column means.

In [ ]:
my_array.mean(axis=0)

In [ ]:
my_array.mean(axis=1)

Calculate the mean of all  values in the array without using the
`mean()` method.

In [ ]:
mean = my_array.sum() / my_array.size
mean

Calculate the row and column means without using the
`mean()` method.

In [ ]:
my_array.sum(axis=0) / my_array.shape[0]

In [ ]:
my_array.sum(axis=1) / my_array.shape[1]

# Roulette

Use Monte Carlo simulation to analyze a player's winning expectation in the following simplified form of a roulette game:

- The croupier spins a wheel divided into 36 equal segments, numbered from 1 to 36.
- The player chooses one of the numbers 1 to 36 and bets 1 euro.
- If the ball lands on the selected number, the player receives his bet
  plus 35 euros back.
- Otherwise, the player loses his bet.

Write a version of the simulation with a `for` loop in Python and
test the performance of this version before and after compilation with
Numba. Then write a vectorized version and test the
performance with and without compiling it with Numba.

*Notes:*
- The NumPy library contains a function
  `np.random.randint(low, high, size=None)`, which you can use to
  create an array with Shape `size` containing uniformly distributed
  random numbers between `low` (inclusive) and `high` (exclusive).
- If `np.random.randint()` is called with only two arguments it returns
  a single number.
- The NumPy library contains a function
  `np.random.binomial(n, p, size=None)` with which you can generate
  binomially distributed random numbers.

In [ ]:
import numpy as np

In [ ]:
def roulette1(n):
    # We can assume that the player always bets on the 1
    # Wir können davon ausgehen, dass der Spieler immer auf die 1 wettet
    money_spent = 0
    money_won = 0
    for i in range(n):
        money_spent += 1
        if np.random.randint(1, 37) == 1:
            money_won += 36
    return (money_won - money_spent) / n

In [ ]:
def test_roulette(roulette):
    np.random.seed(123)
    for n in [1000, 100_000, 1_000_000]:
        %time print(f"Gewinnerwartung ist {100 * roulette(n):.1f}% ({n} Versuche)")

In [ ]:
test_roulette(roulette1)

In [ ]:
import numba

roulette1_nb = numba.jit(roulette1)

In [ ]:
test_roulette(roulette1_nb)

In [ ]:
def roulette2(n):
    money_spent = np.ones(n)
    money_won = np.random.binomial(1, 1.0 / 36.0, n) * 36
    return (money_won - money_spent).sum() / n

In [ ]:
test_roulette(roulette2)

In [ ]:
roulette2_nb = numba.jit(roulette2)

In [ ]:
test_roulette(roulette2_nb)

In [ ]:
def roulette3(n):
    money_spent = n
    money_won = np.random.binomial(n, 1.0 / 36.0) * 36
    return (money_won - money_spent) / n

In [ ]:
test_roulette(roulette3)

In [ ]:
roulette3_nb = numba.jit(roulette3)

In [ ]:
test_roulette(roulette3_nb)