# Erzeugen von NumPy Arrays

Erzeugen Sie folgende NumPy Arrays:

```python
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

```python
array([0.  , 1.25, 2.5 , 3.75, 5.  ])
```

```python
array([ 1,  3, 12, 92])
```

```python
array([[1, 2, 3, 4],
       [5, 6, 7, 8]])
```

```python
array([[[0, 2, 4, 6],
        [1, 3, 5, 7]],

       [[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[9, 8, 7, 6],
        [5, 4, 3, 2]]])
```

Ein $2\times 8$ Array, das gleichverteilte Zufallszahlen in $[0, 1)$ enthält.

```python
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])
```

Einen Vektor der Länge 5, der normalverteilte Zahlen enthält.

Ein $3 \times 4$ Array, das normalverteilte Zahlen mit Mittelwert $5$ und Standardabweichung $0.5$ enthält.

## Gleichungssysteme

Lösen Sie folgendes Gleichungssystem:

$x_1 - x_2 + 2x_3 = 6$

$2x_1 + 3x_2 + 2x_3 = 8$

$3x_1 + 2x_2 + x_3 = 8$

# Erzeugen von NumPy Arrays 2

Erzeugen Sie das folgende NumPy Array:

```python
array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30],
       [32, 34, 36, 38]])
```

Erzeugen Sie das folgende NumPy Array:

```python
array([[10, 19, 28, 37, 46, 55],
       [13, 22, 31, 40, 49, 58],
       [16, 25, 34, 43, 52, 61]])
```

# Extrema

Erzeugen Sie einen Vektor der Länge 100 mit Zufallswerten, die im Intervall
$[10, 20)$ gleichverteilt sind.

Berechnen Sie Minimum und Maximum der im Vektor
enthaltenen Werte sowie die Positionen von Minimum und Maximum.

# Mittelwert

Erzeugen Sie ein $6 \times 8$ Array, das standardverteilten Zahlen mit
Mittelwert $2$ und Standardabweichung $1$ enthält.



Berechnen Sie den Mittelwert aller darin vorkommenden Werte.


Berechnen Sie die zeilen- und spaltenweisen Mittelwerte.

Berechnen Sie den Mittelwert aller vorkommenden Werte ohne Verwendung der
Methode `mean()`.

Berechnen Sie die zeilen- und spaltenweisen Mittelwerte ohne Verwendung der
Methode `mean()`.

# Roulette

Analysieren Sie die Gewinnerwartung eines Spielers in folgender
vereinfachter Form eines Roulettespiels mittels Monte Carlo Simulation:

- Der Kessel ist in 36 Zahlen unterteilt.
- Der Spieler wählt eine der Zahlen 1 bis 36 und wettet 1 Euro.
- Fällt die Kugel auf die gewählte Zahl, so erhält der Spieler seinen Einsatz
  plus 35 Euro zurück.
- Andernfalls verliert der Spieler seinen Einsatz.

Schreiben Sie eine Version der Simulation mit `for`-Schleife in Python und
testen Sie die Performance dieser Version vor und nach Kompilierung mit
Numba. Schreiben Sie dann eine vektorisierte Version und testen Sie deren
Performance in beiden Fällen.

*Hinweise:*
- Die NumPy Bibliothek enthält eine Funktion
  `np.random.randint(low, high, size=None)`, mit der Sie ein Array mit Shape
  `size` erzeugen können, das gleichverteilte Zufallszahlen zwischen `low`
  (inklusive) und `high` (exklusive) enthält.
- Wird `np.random.randint()` mit nur zwei Argumenten aufgerufen, so gibt es
  eine einzige Zahl zurück.
- Die NumPy Bibliothek enthält eine Funtion
  `np.random.binomial(n, p, size=None)`, mit der Sie binomialverteilte
  Zufallszahlen erzeugen können.