# Creating NumPy arrays

Create the following NumPy arrays:

```pythons
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

```pythons
array([0. , 1.25, 2.5 , 3.75, 5. ])
```

```pythons
array([ 1, 3, 12, 92])
```

```pythons
array([[1, 2, 3, 4],
       [5, 6, 7, 8]])
```

```pythons
array([[[0, 2, 4, 6],
        [1, 3, 5, 7]],

       [[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[9, 8, 7, 6],
        [5, 4, 3, 2]]])
```

A $2\times 8$ array containing uniformly distributed random numbers in $[0, 1)$.

```pythons
array([[1st, 0th, 0th],
       [0th, 1st, 0th],
       [0th, 0th, 1st]])
```

A vector of length 5 containing normally distributed numbers.

A $3 \times 4$ array containing normally distributed numbers with mean $5$ and standard deviation $0.5$.

## Systems of equations

Solve the following system of equations:

$x_1 - x_2 + 2x_3 = 6$

$2x_1 + 3x_2 + 2x_3 = 8$

$3x_1 + 2x_2 + x_3 = 8$

# Create NumPy arrays 2

Create the following NumPy array:

```pythons
array([[ 0, 2, 4, 6],
       [8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30],
       [32, 34, 36, 38]])
```

Create the following NumPy array:

```pythons
array([[10, 19, 28, 37, 46, 55],
       [13, 22, 31, 40, 49, 58],
       [16, 25, 34, 43, 52, 61]])
```

# Extreme values

Generate a vector of length 100 containing random values equally
distributed in the interval $[10, 20)$.

Calculate minimum and maximum of the values
contained in the vector as well as the indices of minimum and maximum.


# Average

Create a $6 \times 8$ array with numbers normally distributed with
mean $2$ and standard deviation $1$.

Calculate the mean of all values in the array.

Calculate the row and column means.

Calculate the mean of all  values in the array without using the
`mean()` method.

Calculate the row and column means without using the
`mean()` method.

# Roulette

Use Monte Carlo simulation to analyze a player's winning expectation in the following simplified form of a roulette game:

- The croupier spins a wheel divided into 36 equal segments, numbered from 1 to 36.
- The player chooses one of the numbers 1 to 36 and bets 1 euro.
- If the ball lands on the selected number, the player receives his bet
  plus 35 euros back.
- Otherwise, the player loses his bet.

Write a version of the simulation with a `for` loop in Python and
test the performance of this version before and after compilation with
Numba. Then write a vectorized version and test the
performance with and without compiling it with Numba.

*Notes:*
- The NumPy library contains a function
  `np.random.randint(low, high, size=None)`, which you can use to
  create an array with Shape `size` containing uniformly distributed
  random numbers between `low` (inclusive) and `high` (exclusive).
- If `np.random.randint()` is called with only two arguments it returns
  a single number.
- The NumPy library contains a function
  `np.random.binomial(n, p, size=None)` with which you can generate
  binomially distributed random numbers.