# Playground

Ein leeres Notebook für Experimente und kleine Beispiele.

In [1]:
[1, 2, 3] + [4, 5]

[1, 2, 3, 4, 5]

In [2]:
import numpy as np

In [3]:
np.array([1, 2, 3]) + np.array([2, 3, 4])

array([3, 5, 7])

In [4]:
a1 = np.array([1, 2, 3])
a2 = np.array([2, 3, 4])

In [5]:
a1 + a2

array([3, 5, 7])

In [6]:
a1 * a2

array([ 2,  6, 12])

In [7]:
a1 @ a2.T

20

In [8]:
a1.T @ a2

20

In [9]:
m1 = np.array([[1, 2, 3], [2, 3, 4]])

In [10]:
m1 * a1

array([[ 1,  4,  9],
       [ 2,  6, 12]])

In [11]:
[1, 2, 3].copy()

[1, 2, 3]

In [13]:
my_list = [1, 2, 3]
your_list = my_list.copy()
your_list.append(4)
print(my_list, your_list)

[1, 2, 3] [1, 2, 3, 4]


In [14]:
list_of_lists = [[1, 2, 3], [2, 3, 4]]
list_copy = list_of_lists.copy()

In [20]:
class Kfz:
    def __init__(self, hersteller):
        self.hersteller = hersteller
        
    def to_string(self, name="<unbenannt>"):
        return f"Der Hersteller vom Auto {name} ist {self.hersteller}."

In [22]:
kfz = Kfz("BMW")
kfz.to_string("kfz")

'Der Hersteller vom Auto kfz ist BMW.'

In [23]:
def print_kfz(kfz: Kfz):
    print(kfz.to_string())