In [1]:
import numpy as np

In [2]:
vector = np.array([1, 2, 3, 4])

In [3]:
vector

array([1, 2, 3, 4])

In [4]:
vector.shape

(4,)

In [5]:
mat = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [6]:
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [7]:
mat.shape

(3, 4)

In [8]:
mat.sum()

78

In [10]:
mat.sum(axis=0)

array([15, 18, 21, 24])

In [11]:
mat.sum(axis=1)

array([10, 26, 42])

In [12]:
vector @ vector

30

In [13]:
mat.mean()

6.5

In [14]:
mat.mean(axis=0)

array([5., 6., 7., 8.])

In [15]:
mat.mean(axis=1)

array([ 2.5,  6.5, 10.5])

In [16]:
tensor = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [17]:
tensor

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [18]:
tensor.shape

(2, 2, 2)

In [19]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [20]:
np.array(list(range(10)))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
range(1.0, 10.0)

TypeError: 'float' object cannot be interpreted as an integer

In [22]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(10.0)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [24]:
np.arange(10).dtype

dtype('int64')

In [25]:
np.arange(10.0).dtype

dtype('float64')

In [26]:
np.arange(2, 10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.arange(2, 10, 3)

array([2, 5, 8])

In [28]:
np.arange(1, 2, 0.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [29]:
np.linspace(0.1, 1.0, 10)

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [30]:
np.arange(0.1, 1.1, 0.1)

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [31]:
np.linspace(0.0, 1.0, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [32]:
np.zeros(3)

array([0., 0., 0.])

In [33]:
np.zeros(3).shape

(3,)

In [34]:
np.zeros((3,))

array([0., 0., 0.])

In [35]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [36]:
np.zeros((3, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [39]:
np.zeros((2, 3, 4), dtype=np.int32)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int32)

In [40]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [46]:
np.empty((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [47]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [48]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [49]:
np.eye(3, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])