In [1]:
import numpy as np


# Attributes of arrays

In [2]:
int_vector = np.arange(36)
float_vector = np.arange(36.0)
small_float_vector = np.arange(36.0, dtype=np.float16)

In [3]:
small_float_vector

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35.], dtype=float16)

In [4]:
rng = np.random.default_rng(42)

In [8]:
int_matrix = rng.integers(low=0, high=10, size=(3, 5))

In [9]:
int_matrix

array([[4, 2, 0, 5, 8],
       [0, 8, 8, 2, 6],
       [1, 7, 7, 3, 0]])

In [10]:
tensor = rng.random(size=(3, 4, 5))

In [11]:
tensor

array([[[0.89312112, 0.7783835 , 0.19463871, 0.466721  , 0.04380377],
        [0.15428949, 0.68304895, 0.74476216, 0.96750973, 0.32582536],
        [0.37045971, 0.46955581, 0.18947136, 0.12992151, 0.47570493],
        [0.22690935, 0.66981399, 0.43715192, 0.8326782 , 0.7002651 ]],

       [[0.31236664, 0.8322598 , 0.80476436, 0.38747838, 0.2883281 ],
        [0.6824955 , 0.13975248, 0.1999082 , 0.00736227, 0.78692438],
        [0.66485086, 0.70516538, 0.78072903, 0.45891578, 0.5687412 ],
        [0.139797  , 0.11453007, 0.66840296, 0.47109621, 0.56523611]],

       [[0.76499886, 0.63471832, 0.5535794 , 0.55920716, 0.3039501 ],
        [0.03081783, 0.43671739, 0.21458467, 0.40852864, 0.85340307],
        [0.23393949, 0.05830274, 0.28138389, 0.29359376, 0.66191651],
        [0.55703215, 0.78389821, 0.66431354, 0.40638686, 0.81402038]]])

In [12]:
int_vector.dtype

dtype('int64')

In [13]:
float_vector.dtype

dtype('float64')

In [14]:
small_float_vector.dtype

dtype('float16')

In [15]:
int_vector.shape

(36,)

In [16]:
int_matrix.shape

(3, 5)

In [17]:
tensor.shape

(3, 4, 5)

In [18]:
tensor.size

60

In [19]:
float_vector.size

36

In [20]:
int_vector.itemsize

8

In [21]:
small_float_vector.itemsize

2

In [22]:
np.info(int_matrix)

class:  ndarray
shape:  (3, 5)
strides:  (40, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x55f98726eef0
byteorder:  little
byteswap:  False
type: int64



# Changing Shape and Size

## Changing the Shape

In [23]:
float_vector.shape

(36,)

In [24]:
float_matrix = float_vector.reshape((6, 6))

In [25]:
float_matrix

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23.],
       [24., 25., 26., 27., 28., 29.],
       [30., 31., 32., 33., 34., 35.]])

In [26]:
np.info(float_matrix)

class:  ndarray
shape:  (6, 6)
strides:  (48, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x55f9867cf600
byteorder:  little
byteswap:  False
type: float64


In [27]:
float_matrix.reshape(3, 12)

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.],
       [24., 25., 26., 27., 28., 29., 30., 31., 32., 33., 34., 35.]])

In [28]:
float_matrix

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23.],
       [24., 25., 26., 27., 28., 29.],
       [30., 31., 32., 33., 34., 35.]])

In [29]:
float_vector.reshape(20, 20)

ValueError: cannot reshape array of size 36 into shape (20,20)

In [31]:
m1 = float_vector.reshape(3, 12)
m1

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.],
       [24., 25., 26., 27., 28., 29., 30., 31., 32., 33., 34., 35.]])

In [32]:
np.info(m1)

class:  ndarray
shape:  (3, 12)
strides:  (96, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x55f9867cf600
byteorder:  little
byteswap:  False
type: float64


In [33]:
m2 = float_vector.reshape(3, 12, order="F")
m2

array([[ 0.,  3.,  6.,  9., 12., 15., 18., 21., 24., 27., 30., 33.],
       [ 1.,  4.,  7., 10., 13., 16., 19., 22., 25., 28., 31., 34.],
       [ 2.,  5.,  8., 11., 14., 17., 20., 23., 26., 29., 32., 35.]])

In [34]:
np.info(m2)

class:  ndarray
shape:  (3, 12)
strides:  (8, 24)
itemsize:  8
aligned:  True
contiguous:  False
fortran:  True
data pointer: 0x55f9867cf600
byteorder:  little
byteswap:  False
type: float64


In [35]:
v = np.arange(3)

In [36]:
v

array([0, 1, 2])

In [37]:
v.reshape(3, 1)

array([[0],
       [1],
       [2]])

In [38]:
v.reshape(1, 3)

array([[0, 1, 2]])

In [39]:
v.reshape(-1, 1)

array([[0],
       [1],
       [2]])

In [40]:
v.reshape(1, -1)

array([[0, 1, 2]])

In [41]:
vt = v.reshape(1, 3, 1, 1)
vt

array([[[[0]],

        [[1]],

        [[2]]]])

In [42]:
vt.squeeze()

array([0, 1, 2])

In [43]:
vt.squeeze().shape

(3,)

In [44]:
v2 = np.arange(12).reshape(3, 4)
v2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [45]:
v2.shape

(3, 4)

In [46]:
v3 = v2.reshape(1, 1, 3, 1, 4, 1)

In [47]:
v3.squeeze()

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## Changing the Size

In [48]:
int_vector

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [50]:
int_vector = np.arange(36)

In [51]:
int_vector.resize(10, 10)

In [52]:
int_vector

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [53]:
int_vector.resize(20, 10)

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [54]:
np.resize(int_vector, (20, 10))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

## Transposing